---
    - name: CONFIGURE IPv6 ADDRESSING
      hosts: CSR1kv
      gather_facts: false
      connection: network_cli
      
      tasks:
        - name: SHOW RUNNING CONFIG
          cisco.ios.ios_command:
            commands:
              - show run
          register: output
        
        - name: SAVE OUTPUT ./ios_configurations/
          copy:
            content: "{{ output.stdout[0] }}"
            dest: "router_configurations/CONFIG_output_{{ inventory_hostname }}.txt"
          delegate_to: localhost